services:
- type: web
  name: cinerec-api
  env: docker
  dockerfilePath: ./Dockerfile.api
  plan: free
  region: ohio
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: cinerec-db
      property: connectionString
  - key: REDIS_URL
    value: redis://localhost:6379/0
  - key: TMDB_API_KEY
    sync: false
  - key: GEMINI_API_KEY
    sync: false
  - key: GROQ_API_KEY
    sync: false
  - key: OPENROUTER_API_KEY
    sync: false
  - key: SECRET_KEY
    generateValue: true
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false

databases:
- name: cinerec-db
  plan: free
  region: ohio
  databaseName: cinerec
  user: cinerec_user
